### ISSUE TITLE
A complete code review

### ISSUE THREAD

**Issue by pylover** [pylover/sqlalchemy-media#105]
* Replace internal import with relatives
* Remove all Pychamr's `noinspenctions` due to migration to vim.
* Reduce the max allowable line length to ~99~ 79 chars.
* Write a code of conduct.
* Unused imports

**Comment by jpmn** [comment]
I began work on a few items and will open a PR soon:

* Reduce the max allowable line length to 99 chars.
* Replace internal import with relatives

I also applied pycodestyle and fixed all issues that were detected.

**Comment by pylover** [comment]
Sorry, I voted and loved my own comment by wrong.

**Comment by pylover** [comment]
May thanks, bro.

**Comment by pylover** [comment]
Line width: 79
