### ISSUE TITLE
Purpose of the ImageProcessor's "crop" functionality 

### ISSUE THREAD

**Issue by lelit** [pylover/sqlalchemy-media#113]
I hesitate to pose a probably dummy question, but here it is anyway, possibly just for my own curiosity: what's the "use case" for the hardwired `crop` functionality in the `ImageProcessor`?

While implementing the PIL variant (issue #84, now in its own branch), I struggled to come up with a compatible implementation of the existing wand-based crop functionality: even if it basically works, I think it would need some more tests and refinements.

Recently, actually _using_ the library, I could not find a reasonable use case for an hardwired definition of the crop-area: if any, that comes from the final user (maybe thru some UI), that alone can say what the interesting part of the image is.

Reading issue #107, I wonder if we should remove the declarative crop functionality from the processor, replacing it with a `get_crop()` API, similar to `get_thumbnail()` as suggested there...

What do you think?

**Comment by meyt** [comment]
@lelit you've referred to a very good point, as what i recently involved with, cropping is not simple, and currently in `sqlalchemy-media` we have this useless functionality. 

`crop` should be content-aware, we cannot crop an image just with hard positioning! 

@pylover what you think about drop the `crop` ?

**Comment by pylover** [comment]
Users may use the crop functionality with known coordinations.

For example, getting the crop area from the user while uploading the photo within mobile app and or web front-end. Also, I already used this functionality. How you found it useless?

First of all, it's not useless and if you cannot use it, please do not use it.

**Comment by pylover** [comment]
@jpmn, I suggest you to just crop one time, right when importing the image. and all thumbnails will be generated from the cropped image, So I think the store of a collection of cropped images is not necessary.

**Comment by jpmn** [comment]
My use case is to keep the original image and all the crops coming from it. For example, I take an image of an overview of multiple objects, and I detect all objects in the image and generate cropped images for each of them.
