### ISSUE TITLE
Any estimate for a new release on PyPI?

### ISSUE THREAD

**Issue by lelit** [pylover/sqlalchemy-media#120]
PyPI still have 0.17.1, that has the glitch reported in issue #114.

**Comment by pylover** [comment]
Thanks for reminding.

**Comment by pylover** [comment]
26b3c955d537b83ce547c5f92813f869169c5bc6

**Comment by pylover** [comment]
https://travis-ci.org/pylover/sqlalchemy-media/builds/480622929
