### ISSUE TITLE
How about using gitter?

### ISSUE THREAD

**Issue by YukSeungChan** [pylover/sqlalchemy-media#66]
I think sqlalchemy-media is very useful. Why don't you talk about a feature or a bug in gitter?

**Comment by pylover** [comment]
Interesting, but it always says : Something went wrong. We're sorry. :(

**Comment by YukSeungChan** [comment]
It's okay. I respect your opinion. I think we should close this issue :D

**Comment by pylover** [comment]
In my android phone I cannot login.

**Comment by pylover** [comment]
But I like to leave this issue open till the problem is solved

**Comment by pylover** [comment]
Finally

Join the chat: https://gitter.im/pylover/sqlalchemy-media
