### ISSUE TITLE
get_thumbnail() does not return a Thumbnail

### ISSUE THREAD

**Issue by paulgoetze** [pylover/sqlalchemy-media#72]
Hey @pylover, nice project so far!

I’m trying to create an image and a thumbnail, following the basic setup from the docs (Json, ProfileImage, Person classes):

Suppose I have a Person with an `image` defined I want to create a thumbnail for the image along with storing an uploaded image:

```python
# with file = some file from POST params
#      person = a Person object from the db

with StoreManager(session):
        person.image = ProfileImage.create_from(file)
        person.image.generate_thumbnail(width=100)

        session.add(person)
        session.commit()
```

Creating and uploading the resources works as expected. When I try to access the full urls for the images, it seems like the thumbnail object returned by the `get_thumbnail` is not a Thumbnail object, but a dict, which obviously does not define the `locate()` method.

```python
person.image.locate()  # returns the right url

# this fails:
person.image.get_thumbnail(width=100).locate()
# => AttributeError: 'dict' object has no attribute 'locate'
```

Any idea why this happens? Let me know if/how I can help to solve this.

**Comment by pylover** [comment]
Thank's for reporting. it will be fixed asap.

**Comment by pylover** [comment]
@paulgoetze , Very very thank you.

I added a test case about your issue, and of-course, passed!

**Comment by paulgoetze** [comment]
Awesome, @pylover. Thanks for the quick fix!
