### ISSUE TITLE
Are there any plans for `PIL` support?

### ISSUE THREAD

**Issue by YukSeungChan** [pylover/sqlalchemy-media#84]
Currently `ImageProcessor` utilizes `Wand`, will there be any plans for `PIL` support?

**Comment by pylover** [comment]
Why PIL? Is there any feature that missing in Wand ?

**Comment by YukSeungChan** [comment]
I used Wand for blurring image but I changed it PIL because wand was too slow. How about we can choose other image processing library to use

**Comment by pylover** [comment]
I didn't know that. We can create two classes: `PilAnalyser` and `PilProcessor`

**Comment by pylover** [comment]
@YukSeungChan, what's your idea?

**Comment by YukSeungChan** [comment]
@pylover I think creating `PilAnalyser` and `PilProcessor` is a good idea. I'm busy working on different project currently, so I was going to work on this when I have some time.

**Comment by pylover** [comment]
There is no hurry at all! Thank you for the good idea

**Comment by jpmn** [comment]
Wand has a dependency on ImageMagick, I would really like to not have this dependency for simple resizing and cropping operations. Any help needed for this?

**Comment by pylover** [comment]
@jpmn, Thanks, I have a double barrel now(Two days). So I'll implement this feature ASAP.

**Comment by lelit** [comment]
I'm sorry I somewhat lost my sync with the plan on this since my latest work has been moved into the `implementpillowbasedimageprocessor` branch, due to a focus switch...

As said, if there's anything I can do to help progress...

**Comment by pylover** [comment]
@lelit, No worry at all. I'll continue your branch.

And thanks a lot for the responsibility.

**Comment by pylover** [comment]
I decided to completely migrate to PIL because compatibility is always a serious headache.

A lot of unnecessary dependency inversion not worst. wand users may implement their very own Analyzers and or processors.
